export const GENERAL_ERROR                  = 'GENERAL_ERROR';

export const NOT_AUTHORIZED                 = 'NOT_AUTHORIZED';
export const USER_NOT_FOUND                 = 'USER_NOT_FOUND';
export const SIGN_IN_GENERAL                = 'SIGN_IN_GENERAL';
export const SIGN_IN_INVALID_EMAIL          = 'SIGN_IN_INVALID_EMAIL';
export const SIGN_IN_INVALID_PASSWORD       = 'SIGN_IN_INVALID_PASSWORD';
export const EXPIRED_VERIFICATION_CODE      = 'EXPIRED_VERIFICATION_CODE';
export const VERIFY_REGISTRATION_GENERAL    = 'VERIFY_REGISTRATION_GENERAL';
export const VERIFY_REGISTRATION_INVALID_EMAIL = 'VERIFY_REGISTRATION_INVALID_EMAIL';
export const VERIFY_REGISTRATION_INVALID_CODE  = 'VERIFY_REGISTRATION_INVALID_CODE';

export const SEND_EMAIL_GENERAL             = 'SEND_EMAIL_GENERAL';
export const SEND_EMAIL_INVALId_EMAIL       = 'SEND_EMAIL_INVALId_EMAIL';
export const SEND_EMAIL_NO_EMAIL            = 'SEND_EMAIL_NO_EMAIL';
export const SEND_EMAIL_NO_MESSAGE          = 'SEND_EMAIL_NO_MESSAGE';

export const UPDATE_ATTRS_AND_PASS_INVALID_PARAMETER = 'UPDATE_ATTRS_AND_PASS_INVALID_PARAMETER';
export const UPDATE_ATTRS_AND_PASS_GENERAL  = 'UPDATE_ATTRS_AND_PASS_GENERAL';

export const FETCH_BOTS_GENERAL             = 'FETCH_BOTS_GENERAL';

export const FETCH_USERS_GENERAL            = 'FETCH_USERS_GENERAL';

export const FETCH_CONVERSATIONS_GENERAL    = 'FETCH_CONVERSATIONS_GENERAL';

export const FETCH_MESSAGES_GENERAL         = 'FETCH_MESSAGES_GENERAL';

export const ADD_BOT_GENERAL                = 'ADD_BOT_GENERAL';

export const UPDATE_BOT_GENERAL             = 'UPDATE_BOT_GENERAL';

export const ADD_BOT_FEED_ALL_FIELDS        = 'ADD_BOT_FEED_ALL_FIELDS';
export const ADD_BOT_FEED_GENERAL           = 'ADD_BOT_FEED_GENERAL';

export const SAVE_USER_GENERAL              = 'SAVE_USER_GENERAL';
export const SAVE_USER_INVALID_EMAIL        = 'SAVE_USER_INVALID_EMAIL';
export const FETCH_USER_GENERAL             = 'FETCH_USER_GENERAL';


