export const SEND_EMAIL = 'SEND_EMAIL';
export const USER_UPDATE_ATTRS_AND_PASS = 'USER_UPDATE_ATTRS_AND_PASS';
export const ADD_BOT_GENERAL = 'ADD_BOT_GENERAL';
export const FORCE_SEND_FEEDS = 'FORCE_SEND_FEEDS';
